name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.1.0
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBN_TOKEN }}
      - uses: docker/build-push-action@v6.18.0
        with:
          tags: ghcr.io/${{ github.repository }}
          push: true
          build-args: |
            NPM_TOKEN:${{ secrets.NODE_AUTH_TOKEN }}
          
          
